spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javasecurity?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
mybatis:
  # 打印Sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.tangwh.pojo
  mapper-locations: classpath:mapper/*.xml

