spring:
  mail:
    host: smtp.163.com
    username: t2678691035@163.com
    #授权码:
    password: twh123456
    default-encoding: UTF-8
    protocol:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            # 邮件的日志过程 打印
        debug: true
